message = "Это мое секретное сообщение из файла!"
api_key = "xyz123abc987"
port = 8501
is_production = false



# Секция для настроек базы данных
[database]
host = "localhost"
user = "admin"
password = "super_secret_password_12345"

# Секция для внешнего API
[weather_api]
key = "another-secret-api-key"


